### ISSUE TITLE
Error: Undefined is not an object evaluating ('native.preload')

### ISSUE THREAD

**Issue by aguel** [tradle/react-native-facetec-zoom#1]
Compiled but getting runtime error "Error: Undefined is not an object evaluating ('native.preload')"

Not sure if this is SDK compatibility issue but im using the latest ZoomSDK 7.0.14 since the link to your S3 file for 7.0.8 is broken.

**Comment by aguel** [comment]
Any active link for SDK 7.0.8?

**Comment by mvayngrib** [comment]
hi @aguel, you can download the sdk from https://dev.zoomlogin.com/zoomsdk/#/downloads

**Comment by aguel** [comment]
I mean the latest SDK from FaceTec website it 7.0.14 and doesnt work well
with this release.

**Comment by mvayngrib** [comment]
the error seems to indicate you haven't linked the library. Did you run `react-native link react-native-facetec-zoom`? Can you check to make sure that in Build Phases, under Link Binary With Libraries, you see both `libRNReactNativeZoomSdk.a` and `ZoomAuthenticationHybrid.framework`?

**Comment by aguel** [comment]
Yes  "react-native link react-native-facetec-zoom" done as per instruction
in github.

Build phases -> Link Binary with Libraries checked for both
ibRNReactNativeZoomSdk.a and ZoomAuthenticationHybrid.framework

Basically application can compile and run successfully but crashing on  error "Error: Undefined is not an object evaluating ('native.preload')"

**Comment by aguel** [comment]
For strange reason, im getting new set of errors something like shown below. Any idea?

"Undefined symbols for architecture x86_64:
  "protocol descriptor for Swift.Equatable", referenced from:
      protocol conformance descriptor for __C.ZoomVerificationStatus : Swift.Equatable in __C_Synthesized in libRNReactNativeZoomSdk.a(ZoomAuth.o)
  "method descriptor for static Swift.Equatable.== infix(A, A) -> Swift.Bool", referenced from:
      protocol conformance descriptor for __C.ZoomVerificationStatus : Swift.Equatable in __C_Synthesized in libRNReactNativeZoomSdk.a(ZoomAuth.o)
  "method descriptor for Swift.RawRepresentable.init(rawValue: A.RawValue) -> A?", referenced from:
      protocol conformance descriptor for __C.ZoomVerificationStatus : Swift.RawRepresentable in __C_Synthesized in libRNReactNativeZoomSdk.a(ZoomAuth.o)
  "method descriptor for Swift.RawRepresentable.rawValue.getter : A.RawValue", referenced from:
      protocol conformance descriptor for __C.ZoomVerificationStatus : Swift.RawRepresentable in __C_Synthesized in libRNReactNativeZoomSdk.a(ZoomAuth.o)
  "associated type descriptor for RawValue", referenced from:
      protocol conformance descriptor for __C.ZoomVerificationStatus : Swift.RawRepresentable in __C_Synthesized in libRNReactNativeZoomSdk.a(ZoomAuth.o)
  "__swift_FORCE_LOAD_$_swiftMetal", referenced from:
      __swift_FORCE_LOAD_$_swiftMetal_$_RNReactNativeZoomSdk in libRNReactNativeZoomSdk.a(ZoomAuth.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftMetal_$_RNReactNativeZoomSdk)
  "__swift_FORCE_LOAD_$_swiftCoreFoundation", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreFoundation_$_RNReactNativeZoomSdk in libRNReactNativeZoomSdk.a(ZoomAuth.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreFoundation_$_RNReactNativeZoomSdk)
  "__swift_FORCE_LOAD_$_swiftDarwin", referenced from:
      __swift_FORCE_LOAD_$_swiftDarwin_$_RNReactNativeZoomSdk in libRNReactNativeZoomSdk.a(ZoomAuth.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDarwin_$_RNReactNativeZoomSdk)
  "__swift_FORCE_LOAD_$_swiftFoundation", referenced from:
      __swift_FORCE_LOAD_$_swiftFoundation_$_RNReactNativeZoomSdk in libRNReactNativeZoomSdk.a(ZoomAuth.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftFoundation_$_RNReactNativeZoomSdk)
  "value witness table for Builtin.Int64", referenced from:
      type metadata for __C.ZoomDevicePartialLivenessResult in libRNReactNativeZoomSdk.a(ZoomAuth.o)
      type metadata for __C.ZoomVerificationStatus in libRNReactNativeZoomSdk.a(ZoomAuth.o)"

**Comment by aguel** [comment]
got it sorted.
