### ISSUE TITLE
Crashing: Image not found

### ISSUE THREAD

**Issue by aguel** [tradle/react-native-facetec-zoom#2]
Got the app crashing with this error: Library not loaded: @rpath/ZoomAuthenticationHybrid.framework/ZoomAuthenticationHybrid
  Referenced from: /Users/xxx/Library/Developer/CoreSimulator/Devices/633DF8C9-A323-428A-BD94-A4F6015FFE37/data/Containers/Bundle/Application/9F63DD87-3E32-4F3A-A636-78C52C4619B1/XXXID.app/XXXID
  Reason: image not found

Any idea?

**Comment by aguel** [comment]
Closing.

**Comment by KamranKhankhail** [comment]
@aguel was you able to fix? I am suffering from same problem.

**Comment by aguel** [comment]
Support from facetec not so good, sad to say
